
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author usuario
 */
public class Numerosprimos extends javax.swing.JFrame {

    /**
     * Creates new form Numerosprimos
     */
    public Numerosprimos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblnumero = new javax.swing.JLabel();
        btncalcular = new javax.swing.JButton();
        txtperfecto = new javax.swing.JTextField();
        txtprimo = new javax.swing.JTextField();
        txtmenor = new javax.swing.JTextField();
        txtsuma = new javax.swing.JTextField();
        txtraiz = new javax.swing.JTextField();
        txtnum = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setText("NUMEROS PRIMOS ");

        lblnumero.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblnumero.setText("INGRESAR UN NUMERO:");

        btncalcular.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btncalcular.setText("CALCULAR");
        btncalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btncalcular)
                    .addComponent(lblnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtraiz, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(txtsuma, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtnum, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtperfecto, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtprimo)
                    .addComponent(txtmenor, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lblnumero))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(btncalcular)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(txtperfecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtprimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(txtmenor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(txtsuma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtraiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalcularActionPerformed
           try {
 // se convierte el texto ingresado en txtnum a un número entero
        int num = Integer.parseInt(txtnum.getText());

        // se valida si el numero ingresado estan entre 500
        if (num <= 500) {
            // Muestra los resultados en los recuadros correspondientes 
            mostrar(txtprimo, Primo(num) ? num + " es un número primo." : num + " no es un número primo.");// "?" se utiliza para abreviar If-else 
            mostrar(txtperfecto, Perfecto(num) ? num + " es un número perfecto." : num + " no es un número perfecto.");
            int suma = Suma(num);
            mostrar(txtmenor, primosmenores(num));
            mostrar(txtsuma, "La suma es: " + suma);
            mostrar(txtraiz, "La raíz es: " + Math.sqrt(suma));
        } else {
            // Muestra un mensaje de error 
            JOptionPane.showMessageDialog(rootPane, "solo puede ingresar numeros menores que 500");
        }
    } catch (NumberFormatException e) {
        // Captura una excepción si el texto no es un número válido
        JOptionPane.showMessageDialog(rootPane, "ingrese otro numero");
    }
}

private boolean Primo(int num) {
    // en esta parte se verifica si es un numero primo 
    if (num < 2) {
        return false;
    }
    for (int i = 2; i <= Math.sqrt(num); i++) {
        if (num % i == 0) {
            return false;
        }
    }
    return true;
}

private boolean Perfecto(int num) {
    // se verifica si es un numero perfecto
    int div = 1;  // se inicializa con 1 ya que todo número es divisible por 1
    for (int i = 2; i <= num / 2; i++) {
        if (num % i == 0) {
            div += i;
        }
    }
    return div == num;
}

private void mostrar(JTextField campo, String resul) {
    // Método para mostrar resultados
    campo.setText(resul);
}

private String primosmenores(int num) {
    // se utiliza este metodo para obtener una cadena de números primos menores que el número
    StringBuilder listaPrimos = new StringBuilder();// es mas eficiente utilizar stringBuilder
    for (int i = 2; i < num; i++) {
        if (Primo(i)) {
            listaPrimos.append(i).append(", ");
        }
    }
    return listaPrimos.toString();
}

private int Suma(int num) {
     // en este metodo se suman los numeros menores al ingresado
    int suma = 0;
    for (int i = 2; i < num; i++) {
        if (Primo(i)) {
            suma += i;
        }
    }
    return suma;
    }//GEN-LAST:event_btncalcularActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Numerosprimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Numerosprimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Numerosprimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Numerosprimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Numerosprimos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblnumero;
    private javax.swing.JTextField txtmenor;
    private javax.swing.JTextField txtnum;
    private javax.swing.JTextField txtperfecto;
    private javax.swing.JTextField txtprimo;
    private javax.swing.JTextField txtraiz;
    private javax.swing.JTextField txtsuma;
    // End of variables declaration//GEN-END:variables

    
}
